---
  - name: create reports folder
    file:
      path: "{{ reports_folder }}"
      recurse: yes
      mode: 0770
      owner: root
      group: root
  - name: Run ZAP container for {{ web_url }} scann
    docker_container:
      name: "{{container_name}}"
      image: "{{image_name}}"
      volumes: "{{ reports_folder }}:/zap/wrk:rw"
      command: "zap-baseline.py -t {{ web_url }} -r {{ container_name }}_report.html"
      
  - name: get report log
    raw: "docker logs -f {{container_name}}"
    register: scan_output
  - name: save report locally
    local_action: copy content={{ scan_output }} dest=report.html 
    become: false
  - debug:
      msg: "{{scan_output}}"

