# hosts => adresse ip ou bloc dans l'inventory
- hosts: all
  become: true
  vars:
    docker_debian_key: https://download.docker.com/linux/ubuntu/gpg
    docker_debian_base_repos: deb [arch=amd64] https://download.docker.com/linux/ubuntu
    debian_relase:
  tasks:
    - name: add docker gpg key
      apt_key:
        url : "{{docker_debian_key}}"
        state: present
      when:
        ansible_facts["os_family"] == "Debian"
    - name: add docker repository
      apt_repository:
        repo: " {{docker_debian_base_repos}} {{ ansible_facts['distribution_release'] }} stable"
      when:
        ansible_facts["os_family"] == "Debian"
    - name: install docker component
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
      notify: start docker service
      when:
        ansible_facts["os_family"] == "Debian"
    
    
    - name: add docker repository redhat 1
      yum:
        name: yum-utils 
        update_cache: yes
      when:
        ansible_facts["os_family"] == "RedHat"
    - name: add docker repository redhat 2
      command:
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when:
        ansible_facts["os_family"] == "RedHat"
    - name: install docker component
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
      notify: start docker service
      when:
        ansible_facts["os_family"] == "RedHat" 
    # - name: start docker service
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes
  handlers:
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes
    

    
